# Generated by Django 5.2.5 on 2025-12-02 10:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assets',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('asset_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('azure_blob_name', models.CharField(max_length=500)),
                ('file_size', models.BigIntegerField()),
                ('category', models.CharField(choices=[('item', 'Clothing Items'), ('body', 'Body Images'), ('generated', 'Generated Images')], max_length=50)),
                ('part', models.CharField(blank=True, choices=[('upper', 'Upper'), ('lower', 'Lower'), ('full_set', 'Full Set')], max_length=50, null=True)),
                ('display_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('available', 'Available'), ('failed', 'Failed')], db_index=True, default='available', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='GenerationTask',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('task_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('clothing_upload_ids', models.JSONField(default=list)),
                ('generator_type', models.CharField(db_index=True, max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('provider_task_id', models.CharField(blank=True, max_length=200, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('body_asset', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_as_body_in_generations', to='api.assets')),
                ('result_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_by_task', to='api.assets')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='UploadTask',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('task_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('uploading', 'Uploading'), ('uploaded', 'Uploaded'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='upload_task', to='api.assets')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.AddIndex(
            model_name='assets',
            index=models.Index(fields=['user', 'category', 'status'], name='api_assets_user_id_f1fdd9_idx'),
        ),
        migrations.AddIndex(
            model_name='generationtask',
            index=models.Index(fields=['user', 'status'], name='api_generat_user_id_fed050_idx'),
        ),
    ]
