# Generated by Django 5.2.5 on 2025-12-20 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothing',
            name='currency',
            field=models.CharField(default='EUR', max_length=10),
        ),
    ]
