# Generated by Django 5.2.5 on 2025-12-20 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clothing', '0002_clothing_currency'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clothing',
            old_name='image_url',
            new_name='azure_blob_name',
        ),
    ]
