# Generated by Django 5.2.5 on 2025-12-20 19:09

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clothing', '0003_rename_image_url_clothing_azure_blob_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Favorite',
            new_name='FavoriteClothing',
        ),
    ]
