# Generated by Django 5.2.5 on 2025-12-21 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothing', '0004_rename_favorite_favoriteclothing'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothing',
            name='colors',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
