# Generated by Django 5.2.5 on 2025-12-21 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothing', '0005_clothing_colors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothing',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
